name: reproductor_cloud
description: Reproductor de musica en streaming con Supabase Storage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  audio_metadata_reader: ^1.4.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http: ^1.2.0
  just_audio: ^0.9.40
  path_provider: ^2.1.2
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
